Repository SpasMilenkov/UniTrack, pull requests merged in 2023-12, with the labels that each got.

#60 53 database rework for enhanced relationships and features
  UniTrackBackend/UniTrackBackend.Data.Models/Absence.cs
  UniTrackBackend/UniTrackBackend.Data.Models/Grade.cs
  UniTrackBackend/UniTrackBackend.Data.Models/Mark.cs
  UniTrackBackend/UniTrackBackend.Data.Models/Parent.cs
  UniTrackBackend/UniTrackBackend.Data.Models/Student.cs
  UniTrackBackend/UniTrackBackend.Data/Database/UniTrackDbContext.cs
  UniTrackBackend/UniTrackBackend.Data/Migrations/UniTrackDbContextModelSnapshot.cs
Labels: enhancement

#82 Fix the seeding mechanism relying on hardcoded properties
  UniTrackBackend/UniTrackBackend.Data/Seeding/DataSeeder.cs
Labels: bug

#90 Convert the dictionaries to arrays. Improve logging
  UniTrackBackend/UniTrackBackend.Api.ViewModels/ResultViewModels/StudentAnalysisResultViewModel.cs
  UniTrackBackend/UniTrackBackend.Data/Repositories/MarkRepository.cs
  UniTrackBackend/UniTrackBackend.Data/UniTrackBackend.Data.csproj
  UniTrackBackend/UniTrackBackend.Services/AnalysisService/AnalysisService.cs
Labels: enhancement

#108 96 remove elective subject entity
  UniTrackBackend/UniTrackBackend.Data.Models/ElectiveSubject.cs
  UniTrackBackend/UniTrackBackend.Data/Database/UniTrackDbContext.cs
  UniTrackBackend/UniTrackBackend.Data/Migrations/20231211212427_InitialCreate.Designer.cs
  UniTrackBackend/UniTrackBackend.Data/Migrations/UniTrackDbContextModelSnapshot.cs
  UniTrackBackend/UniTrackBackend.Data/UnitOfWork.cs
Labels: enhancement

#113 111 documentation of undocumented controllers
  UniTrackBackend/UniTrackBackend/Controllers/AbsenceController.cs
  UniTrackBackend/UniTrackBackend/Controllers/AnalysisController.cs
  UniTrackBackend/UniTrackBackend/Controllers/RecommendationController.cs
  UniTrackBackend/UniTrackBackend/Controllers/SchoolController.cs
  UniTrackBackend/UniTrackBackend/Controllers/TeacherController.cs
Labels: documentation

#114 112 migration from moq to fakeiteasy
  UniTrackBackend/UniTrackBackend.Api.Tests/AdminControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/AuthControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/MarkControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/StudentControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/UniTrackBackend.Api.Tests.csproj
  UniTrackBackend/UniTrackBackend.Services.Mappings/Mapper.cs
  UniTrackBackend/UniTrackBackend.Services.Tests/UniTrackBackend.Services.Tests.csproj
  UniTrackBackend/UniTrackBackend/Controllers/AuthController.cs
  UniTrackBackend/UniTrackBackend/Controllers/MarkController.cs
Labels: testing

#115 97 add unit testing for individual services in the backend
  UniTrackBackend/UniTrackBackend.Api.Tests/AbsenceControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/AnalysisControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/ApprovalControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/AuthControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/RecommendationControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/SchoolControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/StudentControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/TeacherControllerTests.cs
  UniTrackBackend/UniTrackBackend.Data.Models/User.cs
  UniTrackBackend/UniTrackBackend.Services/AbsenceService/AbsenceService.cs
  UniTrackBackend/UniTrackBackend.Services/ApprovalService/ApprovalService.cs
  UniTrackBackend/UniTrackBackend/Controllers/AbsenceController.cs
  UniTrackBackend/UniTrackBackend/Controllers/ApprovalController.cs
  UniTrackBackend/UniTrackBackend/Controllers/DummyController.cs
  UniTrackBackend/UniTrackBackend/UniTrackBackend.xml
Labels: testing

#118 117 service layer testing and bug resolution
  UniTrackBackend/UniTrackBackend.Api.Tests/AbsenceControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/AdminControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/AnalysisControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/ApprovalControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/AuthControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/MarkControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/RecommendationControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/StudentControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/TeacherControllerTests.cs
  UniTrackBackend/UniTrackBackend.Data.Commons/IMarkRepository.cs
  UniTrackBackend/UniTrackBackend.Data.Commons/IStudentRepository.cs
  UniTrackBackend/UniTrackBackend.Data.Commons/IUnitOfWork.cs
  UniTrackBackend/UniTrackBackend.Data.Commons/UniTrackBackend.Data.Commons.csproj
  UniTrackBackend/UniTrackBackend.Data/Migrations/20231215185323_InitialCreate.Designer.cs
  UniTrackBackend/UniTrackBackend.Data/Migrations/20231215185323_InitialCreate.cs
  UniTrackBackend/UniTrackBackend.Data/Migrations/UniTrackDbContextModelSnapshot.cs
  UniTrackBackend/UniTrackBackend.Data/Repositories/MarkRepository.cs
  UniTrackBackend/UniTrackBackend.Data/Repositories/StudentRepository.cs
  UniTrackBackend/UniTrackBackend.Data/UnitOfWork.cs
  UniTrackBackend/UniTrackBackend.Services.Tests/AbsenceServiceTests.cs
  UniTrackBackend/UniTrackBackend.Services.Tests/AdminServiceTests.cs
  UniTrackBackend/UniTrackBackend.Services.Tests/AnalysisServiceTests.cs
  UniTrackBackend/UniTrackBackend.Services.Tests/ApprovalServiceTests.cs
  UniTrackBackend/UniTrackBackend.Services.Tests/MarkServiceTests.cs
  UniTrackBackend/UniTrackBackend.Services.Tests/StudentServiceTests.cs
  UniTrackBackend/UniTrackBackend.Services.Tests/TeacherServiceTests.cs
  UniTrackBackend/UniTrackBackend.Services/AbsenceService/AbsenceService.cs
  UniTrackBackend/UniTrackBackend.Services/AbsenceService/IAbsenceService.cs
  UniTrackBackend/UniTrackBackend.Services/AdminService/AdminService.cs
  UniTrackBackend/UniTrackBackend.Services/AdminService/IAdminService.cs
  UniTrackBackend/UniTrackBackend.Services/AnalysisService/AnalysisService.cs
  UniTrackBackend/UniTrackBackend.Services/AnalysisService/IAnalysisService.cs
  UniTrackBackend/UniTrackBackend.Services/ApprovalService/ApprovalService.cs
  UniTrackBackend/UniTrackBackend.Services/ApprovalService/IApprovalService.cs
  UniTrackBackend/UniTrackBackend.Services/Auth/AuthService.cs
  UniTrackBackend/UniTrackBackend.Services/Auth/IAuthService.cs
  UniTrackBackend/UniTrackBackend.Services/MarkService/IMarkService.cs
  UniTrackBackend/UniTrackBackend.Services/MarkService/MarkService.cs
  UniTrackBackend/UniTrackBackend.Services/Messaging/EmailService.cs
  UniTrackBackend/UniTrackBackend.Services/Messaging/IEmailService.cs
  UniTrackBackend/UniTrackBackend.Services/RecommendationService/IRecommendationService.cs
  UniTrackBackend/UniTrackBackend.Services/RecommendationService/RecommendationService.cs
  UniTrackBackend/UniTrackBackend.Services/SchoolService/SchoolService.cs
  UniTrackBackend/UniTrackBackend.Services/StudentService/IStudentService.cs
  UniTrackBackend/UniTrackBackend.Services/StudentService/StudentService.cs
  UniTrackBackend/UniTrackBackend.Services/TeacherService/ITeacherService.cs
  UniTrackBackend/UniTrackBackend.Services/TeacherService/TeacherService.cs
  UniTrackBackend/UniTrackBackend/Controllers/AbsenceController.cs
  UniTrackBackend/UniTrackBackend/Controllers/AdminController.cs
  UniTrackBackend/UniTrackBackend/Controllers/AnalysisController.cs
  UniTrackBackend/UniTrackBackend/Controllers/ApprovalController.cs
  UniTrackBackend/UniTrackBackend/Controllers/AuthController.cs
  UniTrackBackend/UniTrackBackend/Controllers/MarkController.cs
  UniTrackBackend/UniTrackBackend/Controllers/RecommendationController.cs
  UniTrackBackend/UniTrackBackend/Controllers/StudentsController.cs
  UniTrackBackend/UniTrackBackend/Controllers/TeacherController.cs
  UniTrackBackend/UniTrackBackend/Program.cs
  UniTrackBackend/UniTrackBackend/UniTrackBackend.xml
Labels: testing

#124 Adjust backend for frontend connection
  UniTrackBackend/UniTrackBackend.Api.Tests/ApprovalControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/AuthControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/StudentControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.Tests/TeacherControllerTests.cs
  UniTrackBackend/UniTrackBackend.Api.ViewModels/ResultViewModels/LoginResultViewModel.cs
  UniTrackBackend/UniTrackBackend.Api.ViewModels/ResultViewModels/SubjectResultViewModel.cs
  UniTrackBackend/UniTrackBackend.Api.ViewModels/ResultViewModels/TeacherResultViewModel.cs
  UniTrackBackend/UniTrackBackend.Api.ViewModels/StudentApprovalViewModel.cs
  UniTrackBackend/UniTrackBackend.Api.ViewModels/StudentViewModel.cs
  UniTrackBackend/UniTrackBackend.Api.ViewModels/SubjectViewModel.cs
  UniTrackBackend/UniTrackBackend.Api.ViewModels/TeacherApprovalViewModel.cs
  UniTrackBackend/UniTrackBackend.Api.ViewModels/TeacherViewModel.cs
  UniTrackBackend/UniTrackBackend.Data.Commons/IStudentRepository.cs
  UniTrackBackend/UniTrackBackend.Data.Commons/ITeacherRepository.cs
  UniTrackBackend/UniTrackBackend.Data.Commons/IUnitOfWork.cs
  UniTrackBackend/UniTrackBackend.Data/Repositories/StudentRepository.cs
  UniTrackBackend/UniTrackBackend.Data/Repositories/TeacherRepository.cs
  UniTrackBackend/UniTrackBackend.Data/Seeding/DataSeeder.cs
  UniTrackBackend/UniTrackBackend.Data/UnitOfWork.cs
  UniTrackBackend/UniTrackBackend.Services.Mappings/IMapper.cs
  UniTrackBackend/UniTrackBackend.Services.Mappings/Mapper.cs
  UniTrackBackend/UniTrackBackend.Services/ApprovalService/ApprovalService.cs
  UniTrackBackend/UniTrackBackend.Services/ApprovalService/IApprovalService.cs
  UniTrackBackend/UniTrackBackend.Services/Auth/AuthService.cs
  UniTrackBackend/UniTrackBackend.Services/Auth/IAuthService.cs
  UniTrackBackend/UniTrackBackend.Services/GradeService/GradeService.cs
  UniTrackBackend/UniTrackBackend.Services/GradeService/IGradeService.cs
  UniTrackBackend/UniTrackBackend.Services/StudentService/IStudentService.cs
  UniTrackBackend/UniTrackBackend.Services/StudentService/StudentService.cs
  UniTrackBackend/UniTrackBackend.Services/SubjectService/ISubjectService.cs
  UniTrackBackend/UniTrackBackend.Services/SubjectService/SubjectService.cs
  UniTrackBackend/UniTrackBackend.Services/TeacherService/ITeacherService.cs
  UniTrackBackend/UniTrackBackend.Services/TeacherService/TeacherService.cs
  UniTrackBackend/UniTrackBackend/Controllers/ApprovalController.cs
  UniTrackBackend/UniTrackBackend/Controllers/AuthController.cs
  UniTrackBackend/UniTrackBackend/Controllers/StudentsController.cs
  UniTrackBackend/UniTrackBackend/Controllers/SubjectController.cs
  UniTrackBackend/UniTrackBackend/Controllers/TeacherController.cs
  UniTrackBackend/UniTrackBackend/Infrastructure/CookieOptionManager.cs
  UniTrackBackend/UniTrackBackend/Program.cs
  UniTrackBackend/UniTrackBackend/UniTrackBackend.xml
Labels: bug, documentation, testing, missing
